Fix SET when pushing a screen from bottom tabs (#6917)
I see that this issue is kinda present in the issue backlog so I've decided to fix it (since it happened to me). 
This is the error that I'm encountering: 

```
java.lang.NullPointerException: Attempt to invoke virtual method 'float java.lang.Float.floatValue()' on a null object reference
        at com.aurelhubert.ahbottomnavigation.AHBottomNavigation.setTitleInactiveTextSizeInSp(AHBottomNavigation.java:1311)
        at com.reactnativenavigation.viewcontrollers.bottomtabs.BottomTabPresenter.lambda$applyOptions$0$BottomTabPresenter(BottomTabPresenter.java:65)
        at com.reactnativenavigation.viewcontrollers.bottomtabs.-$$Lambda$BottomTabPresenter$xw0BqWFLHJmeiaHq_MSiMyHoYmc.run(Unknown Source:4)
        at com.reactnativenavigation.utils.LateInit.perform(LateInit.java:19)
```

basically my assumption is that calling set on titleInactiveTextSize results in the error above.

This should fix it :D